services:
  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - POSTGRES_HOST=dbDev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=falgor123
      - POSTGRES_DB=Kuripot_dev
      - POSTGRES_PORT=5432
    depends_on:
      dbDev:
        condition: service_healthy
    # secrets:
    #   - db-password

    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
          ignore:
            - node_modules/
    command: npm run dev

  client:
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /app
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
    command: npm start

  dbDev:
    image: postgres
    restart: always
    user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Kuripot_dev
      - POSTGRES_PASSWORD=falgor123
    expose:
      - 5432
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbTest:
    image: postgres
    restart: always
    user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Kuripot_test
      - POSTGRES_PASSWORD=falgor123
    expose:
      - 5434
    ports:
      - "5435:5434"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbProd:
    image: postgres
    restart: always
    user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Kuripot_prod
      - POSTGRES_PASSWORD=falgor123
    expose:
      - 5436
    ports:
      - "5437:5436"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

# secrets:
#   db-password:
#     file: db/password.txt