services:
  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
          ignore:
            - node_modules/
    command: npm run dev

  client:
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /app
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
    command: npm start
