# version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=Kuripot
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    command: sh -c "(npx sequelize-cli db:create 2>&1 | grep -q 'already exists' || exit 0) && npx sequelize-cli db:migrate"

  client:
    build:
      context: ./client
    ports:
      - "3000:80"

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Kuripot
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt